# Generated by Django 5.1.3 on 2024-11-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='arquivo_pdf',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='livro',
            name='conteudo_markdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn" target="_blank" rel="noopener noreferrer">Site do ISBN</a>', max_length=13, verbose_name='ISBN'),
        ),
    ]
