# Generated by Django 5.1.3 on 2024-11-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_livro_arquivo_pdf_remove_livro_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancialivro',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.livro'),
        ),
    ]
