# Generated by Django 3.2.25 on 2024-11-04 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_publicacao', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('numero_paginas', models.PositiveIntegerField()),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('idioma', models.CharField(max_length=30)),
                ('conteudo', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='app.autor')),
            ],
        ),
    ]
