# Generated by Django 3.2.25 on 2024-11-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_paginaprincipal_paginasobre_registroleitura_statusleitura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='../media/capas'),
        ),
    ]
